name: java-jre
version: "8u102"
summary: java-jre
description: A part for java-jre 8. It uses zulu runtime of available for targer platform, which performs lot better on arm.

parts:
    # java run time
    java-jre:
        plugin: java-jre
        # zulu supported arcghitectures(armhf, amd64) are already handled by plugin itself
        # define here overide for pluging's defaults, or to add additional architectures
        # example overide:
        # zulu:
        #     amd64: https://www.azul.com/downloads/zulu/zdk-8-ga-linux_x64.tar.gz

